### PR TITLE
Fix Single.ToString() for special values

### LINKED ISSUE #157: Single.ToString not consistent for Infinity and NaN
refer to http://netmf.codeplex.com/workitem/1848

### PR DESCRIPTION
**Pull request by mortezag**
Fix ToString method for float type so that it returns correct strings for NaN, Infinity, and -Infinity values

Fixes #157

### CODE REVIEW

File: Framework/Subset_of_CorLib/System/Single.cs [hunk 1]
```diff
@@ -22,14 +22,31 @@ public struct Single
 
         public override String ToString()
         {
-            return Number.Format(m_value, false, "G", NumberFormatInfo.CurrentInfo);
+            string str = ((Double)m_value).ToString();
```
Comment (smaillet-ms) [inline Framework/Subset_of_CorLib/System/Single.cs]: This seems kinda wonky.... Shouldn't the fic be done in Number.Format directly instead of here? Isn't it possible something else calls Number.Format() that would still get the incorrect behavior?

Comment (mortezag) [inline Framework/Subset_of_CorLib/System/Single.cs]: AFAIK, only Double and Single are using Number.Format method with these parameters. Double class has its own mechanism to find out special values and treat them accordingly. Double also does it at the managed layer (with the help of a few native functions). For the Single type, we do not have those native methods and implementing them is not trivial, so I got help from the Double type.
I agree the it would be better if you could fix it at the native layer but it requires a significant amount to effort (implementing a bunch of native method to recognize special values for the Single type) 
Similarly, bringing the logic to Number class requires modifications to Double types while does not add a lot of value.
I believe it is better to keep the change here for now.

Comment (smaillet-ms) [inline Framework/Subset_of_CorLib/System/Single.cs]: OK, then let's at least add a comment to explain that point.

File: Framework/Subset_of_CorLib/System/Single.cs [hunk 2]
```diff
@@ -22,14 +22,34 @@ public struct Single
 
         public override String ToString()
         {
-            return Number.Format(m_value, false, "G", NumberFormatInfo.CurrentInfo);
+            // Number.Format method is responsible for returning the correct string representation of the value; however, it does not work properly for special values.
```
Comment (smaillet-ms) [inline Framework/Subset_of_CorLib/System/Single.cs]: Can you reflow the comments here, they are really long and don't fit on the screen in a GitHub review...

**Comment by smaillet-ms** [comment]
:+1:
