### PR TITLE
Fix Byte.ToString(X2)

### LINKED ISSUE #133: Byte X2 formatting returns 8 bytes for values above 127 in emulator
```csharp
byte b = 255;
string s = b.ToString("X2");
```

This code returns `"FF"` on device but `"FFFFFFFF"` in the emulator (similarly for all byte values above 127). `"FF"` is expected.

### PR DESCRIPTION
**Pull request by mortezag**
Fixes #133

### CODE REVIEW

File: Framework/Subset_of_CorLib/System/Number.cs [hunk 1]
```diff
@@ -371,7 +371,7 @@ private static String PostProcessInteger(Object value, String original, char for
                     {
                         int len = result.Length;
 
-                        if(value is sbyte)
+                        if(value is sbyte || value is byte)
```
Comment (smaillet-ms) [inline Framework/Subset_of_CorLib/System/Number.cs]: Don't we have a similar signed/unsigned problem below for short vs. ushort?

Comment (mortezag) [inline Framework/Subset_of_CorLib/System/Number.cs]: It seems it does not.

**Comment by smaillet-ms** [comment]
:+1:

File: Framework/Subset_of_CorLib/System/Number.cs (hunk 1 above)
Comment (miloush) [inline Framework/Subset_of_CorLib/System/Number.cs]: I think this is because this "post processing" is actually fixing wrong native output in the case of byte. Anyone reading this fixed code would question the ushort case too.

Might be worth fixing the original cause, e.g. in [corlib_native_System_Number.cpp](../blob/dev/CLR/Libraries/CorLib/corlib_native_System_Number.cpp) changing `char` to `unsigned char` unless there is a compiler reason not to (works for me in the emulator).
```cpp
case DATATYPE_U1:  
hal_snprintf( result, ARRAYSIZE(result), "%.*X", precision,
                                               (unsigned char)value->NumericByRef().u1 );  
break; 
```
